-- main
require('packages')
require('general')
require('keymap')

-- setup
require('setup/alpha')
require('setup/treesitter')
require('setup/lsp')
require('setup/null-ls')
require('setup/ultisnips')
require('setup/fzf')
require('setup/diffview')
require('setup/fugitive')
require('setup/autopairs')
require('setup/autotag')
require('setup/lualine')
require('setup/gitsigns')
require('setup/tree')
require('setup/colors')
require('setup/cmp')
require('setup/floaterm')
require('setup/fidget')
require('setup/symbols-outline')
