-- main
require('general')
require('packages')
require('keymap')

-- setup
require('setup/alpha')
require('setup/treesitter')
require('setup/lsp')
require('setup/fzf')
require('setup/diffview')
require('setup/fugitive')
require('setup/autopairs')
require('setup/autotag')
require('setup/nvim-buddy')
require('setup/lualine')
require('setup/gitsigns')
require('setup/colors')
require('setup/cmp')
require('setup/floaterm')
require('setup/fidget')
require('setup/vimwiki')
require('setup/octo')
require('setup/telescope')
require('setup/oil')
